version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8.0
    container_name: tp_csi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Mot de passe root
      MYSQL_DATABASE: tp_csi_db               # Nom de la base de données
      MYSQL_USER: user                    # Utilisateur
      MYSQL_PASSWORD: userpassword        # Mot de passe de l'utilisateur
    ports:
      - "3306:3306"  # Expose le port MySQL
    volumes:
      - ./mysql_data:/var/lib/mysql       # Pour persister les données
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Fichier SQL d'initialisation
